// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../src/components/error/403.vue')['default']
    404: typeof import('./../src/components/error/404.vue')['default']
    500: typeof import('./../src/components/error/500.vue')['default']
    BaseFooter: typeof import('./../src/components/Cache/BaseFooter.vue')['default']
    BaseHeader: typeof import('./../src/components/Cache/BaseHeader.vue')['default']
    BaseInfo: typeof import('./../src/components/Cache/BaseInfo.vue')['default']
    BasePort: typeof import('./../src/components/Cache/BasePort.vue')['default']
    BillingStandards: typeof import('./../src/components/Cache/BillingStandards.vue')['default']
    CacheBases: typeof import('./../src/components/Cache/CacheBases.vue')['default']
    CodeFragment: typeof import('./../src/components/Cache/CodeFragment.vue')['default']
    CodeHight: typeof import('./../src/components/CodeHight/index.vue')['default']
    Configuration: typeof import('./../src/components/Cache/Configuration.vue')['default']
    CountTo: typeof import('./../src/components/CountTo/index.vue')['default']
    Echarts: typeof import('./../src/components/Echarts/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HeaderCount: typeof import('./../src/components/Cache/HeaderCount.vue')['default']
    HomePageFooter: typeof import('./../src/components/Home/HomePageFooter.vue')['default']
    HomePageHeader: typeof import('./../src/components/Home/HomePageHeader.vue')['default']
    'IAntDesign:caretDownOutlined': typeof import('~icons/ant-design/caret-down-outlined')['default']
    'IEp:loading': typeof import('~icons/ep/loading')['default']
    'IEp:warningFilled': typeof import('~icons/ep/warning-filled')['default']
    StatusIcon: typeof import('./../src/components/Cache/StatusIcon.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TableOnMobile: typeof import('./../src/components/Home/TableOnMobile.vue')['default']
    TableOnPc: typeof import('./../src/components/Home/TableOnPc.vue')['default']
    TopCard: typeof import('./../src/components/Home/TopCard.vue')['default']
  }
}

export { }
