// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./../src/components/error/404.vue')['default']
    BaseFooter: typeof import('./../src/components/Cache/BaseFooter.vue')['default']
    BaseHeader: typeof import('./../src/components/Cache/BaseHeader.vue')['default']
    BaseInfo: typeof import('./../src/components/Cache/BaseInfo.vue')['default']
    BasePort: typeof import('./../src/components/Cache/BasePort.vue')['default']
    BillingStandards: typeof import('./../src/components/Cache/BillingStandards.vue')['default']
    CacheBases: typeof import('./../src/components/Cache/CacheBases.vue')['default']
    ChartList: typeof import('./../src/components/Cache/ChartList.vue')['default']
    CodeHight: typeof import('./../src/components/CodeHight/index.vue')['default']
    Configuration: typeof import('./../src/components/Cache/Configuration.vue')['default']
    CountTo: typeof import('./../src/components/CountTo/index.vue')['default']
    Docker: typeof import('./../src/components/Cache/SampleCode/Docker.vue')['default']
    Echarts: typeof import('./../src/components/Echarts/index.vue')['default']
    Go: typeof import('./../src/components/Cache/SampleCode/Go.vue')['default']
    HeaderCount: typeof import('./../src/components/Cache/HeaderCount.vue')['default']
    HomePageFooter: typeof import('./../src/components/Home/HomePageFooter.vue')['default']
    HomePageHeader: typeof import('./../src/components/Home/HomePageHeader.vue')['default']
    Java: typeof import('./../src/components/Cache/SampleCode/Java.vue')['default']
    Node: typeof import('./../src/components/Cache/SampleCode/Node.vue')['default']
    Php: typeof import('./../src/components/Cache/SampleCode/Php.vue')['default']
    Python: typeof import('./../src/components/Cache/SampleCode/Python.vue')['default']
    Redis: typeof import('./../src/components/Cache/SampleCode/Redis.vue')['default']
    StatusIcon: typeof import('./../src/components/Cache/StatusIcon.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TableOnMobile: typeof import('./../src/components/Home/TableOnMobile.vue')['default']
    TableOnPc: typeof import('./../src/components/Home/TableOnPc.vue')['default']
    Tabs: typeof import('./../src/components/Tabs.vue')['default']
    TopCard: typeof import('./../src/components/Home/TopCard.vue')['default']
  }
}

export { }
